version = 1

exclude_patterns = [
  "api/migrations/**",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120