# Generated by Django 4.2.11 on 2024-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_avatar_image_alter_category_share_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
