# Generated by Django 4.2.11 on 2024-04-07 18:42

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='share_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=18, max_length=20, prefix='CS'),
        ),
        migrations.AlterField(
            model_name='list',
            name='share_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=18, max_length=20, prefix='LS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=18, max_length=20, prefix='US'),
        ),
    ]
