# Generated by Django 4.2.11 on 2024-04-09 16:04

import api.models.model_template
import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_share_code_alter_list_share_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), api.models.model_template.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='list',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), api.models.model_template.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
