# Generated by Django 4.2.11 on 2024-04-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_useravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravatar',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usertransaction'),
        ),
    ]
