# Generated by Django 4.2.11 on 2024-04-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='question',
            field=models.CharField(default='Cuál prefieres?', max_length=100),
            preserve_default=False,
        ),
    ]
