# Generated by Django 4.2.11 on 2024-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_list_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listanswer',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
