# Generated by Django 4.2.11 on 2024-04-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification_date'),
        ('api', '0014_alter_listanswer_start_date_alter_listcomment_date'),
    ]

    operations = [
    ]
