# Generated by Django 4.2.11 on 2024-05-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_highlightedlist_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='share_code',
            field=models.CharField(max_length=20),
        ),
    ]
