# Generated by Django 4.2.11 on 2024-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_highlightedlist_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listanswer',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
