# Generated by Django 4.2.11 on 2024-05-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_notification_share_code'),
        ('api', '0019_alter_listanswer_start_date'),
    ]

    operations = [
    ]
